### ISSUE TITLE
New v74 update won't launch in unity Game Mode (PCVR)

### ISSUE THREAD

**Issue by quangtnv** [oculus-samples/Unity-MRMotifs#3]
I recently pulled the new update to get the v74 from this repository. After many attempts try to debug this issue, it still not load to the headset when hit "Play". This issue also occur on other projects I'm working with too, after update the  Meta SDK from v72 -> v74, Unity will not load to the headset anymore. Unity only shows a static screen, and in the headset it shows the quest link room. 
If I build it to a executable, it also won't load.
Headset and Quest Link are connected via cable.
The project repo works fine with v72.

Hardware: Quest 3/Pro
Unity Version: 6000.0.42f1
OpenXR version: 1.14.1

**Comment by quangtnv** [comment]
Thanks for your promptly response Robi, 

I don't think the issue has been addressed yet. I re-clone the project again with the default setting, launching in PCVR using Oculus plugin. Same issue, the Play mode won't launch through Quest Link.

Image 1: Using Oculus Plugin only.
![Image](https://github.com/user-attachments/assets/919caa6e-c364-46c9-b738-322da5c51dd7)

Image 2: Quest 3 is connected through Quest Link
![Image](https://github.com/user-attachments/assets/f3952600-bc41-4033-9e16-3b93c0513cbf)

Image 3: Play mode doesn't launch in Quest 3, XR probably did not get initialized correctly in v74.
![Image](https://github.com/user-attachments/assets/2afd11c1-548f-440e-9a61-3af2067e8054)

**Comment by metaRobi** [comment]
Sorry to hear you still have issues. Is this happening in every scene? I think your screenshot is from the Home Scene right?

**Comment by quangtnv** [comment]
> Sorry to hear you still have issues. Is this happening in every scene? I think your screenshot is from the Home Scene right?
Yes, the MRMotifsHome does not launch, this also happens with other projects I'm working with too.




> Hello,
> 
> First of all, sorry to hear that you are blocked, we're trying our best to recreate the issue on our end, but haven't been able so far.
> 
> Before anything, I would like to note that currently there is a known issue with Meta Quest Link and the Depth API and we're working on delivering a fix as soon as possible. Whenever a scene that has the "EnvironmentDepthManager" starts in Link, the client will crash since it can't retrieve depth. There's an open thread here about it : [oculus-samples/Unity-DepthAPI#72](https://github.com/oculus-samples/Unity-DepthAPI/issues/72)
> 
> The issue you are experiencing seems to be different, though, since the opening scene shouldn't have any depth in it. The reason I bring this up is because the moment you'd navigate to the Depth Motifs, you will 100% experience a crash. We're aware of how important Link is for the development process, but until we have fixed the current issues with it, I would like to recommend the [XRSimulator](https://developers.meta.com/horizon/documentation/unity/xrsim-intro/) package instead. It's a great tool and very easy to use.
> 
> That being said, we would greatly appreciate it if you could send us some logs. Firstly, I'd like to take a look at the Meta Quest log located here on Windows:
> 
> C:\Users~USERNAME\AppData\Local\Oculus
> 
> The latest txt file starting with "Client" (there are multiple, we need the latest one). After you experience the crash, this file will be written into with relevant logs.
> 
> Secondly, the Unity editor logs would also be useful in gathering some insight. After you experience the crash, navigate to this path on Windows:
> 
> C:\Users~USERNAME\AppData\Local\Unity\Editor
> 
> And grab the Editor.log file.
> 
> These two files might give us an idea of what's happening.
> 
> Thank you for all the feedback, we appreciate it.

Thanks Jude for your response and your help! To answer your question, no I didn't launch the Depth scene since I aware that's an issue with the SDK and Link. I did use the XRSimulator and it works perfectly, so thank you for that. 

Some digging I found Unity cannot create Subsystem for OVR particularly in v74. 
Again v72 launching find when I checkout previous commit.

Here's the Oculus Client log file:
`[Unity.exe (44236)] 21/03 15:58:10.352 {INFO}    [CAPI] ovr_Initialize success
[Unity.exe (44236)] 21/03 15:58:10.381 {INFO}    [OXR] xrCreateInstance available extensions: XR_KHR_D3D11_enable,XR_KHR_D3D12_enable,XR_KHR_opengl_enable,XR_KHR_vulkan_enable,XR_KHR_vulkan_enable2,XR_KHR_composition_layer_depth,XR_KHR_win32_convert_performance_counter_time,XR_KHR_convert_timespec_time,XR_KHR_composition_layer_cube,XR_KHR_composition_layer_cylinder,XR_KHR_composition_layer_equirect,XR_KHR_visibility_mask,XR_KHR_composition_layer_color_scale_bias,XR_EXT_win32_appcontainer_compatible,XR_EXT_debug_utils,XR_OCULUS_recenter_event,XR_OCULUS_audio_device_guid,XR_FB_color_space,XR_FB_display_refresh_rate,XR_META_performance_metrics,XR_META_headset_id,XR_OCULUS_ovrsession_handle,XR_EXT_hand_interaction,XR_EXT_hand_tracking,XR_FB_hand_tracking_aim,XR_FB_hand_tracking_capsules,XR_FB_hand_tracking_mesh,XR_EXT_hand_tracking_data_source,XR_META_hand_tracking_microgestures,XR_META_simultaneous_hands_and_controllers,XR_FB_body_tracking,XR_META_body_tracking_full_body,XR_META_body_tracking_fidelity,XR_META_body_tracking_calibration,XR_FB_passthrough,XR_META_passthrough_layer_resumed_event,XR_FB_triangle_mesh,XR_META_passthrough_color_lut,XR_META_passthrough_preferences,XR_FB_render_model,XR_FB_spatial_entity_container,XR_FB_scene,XR_FB_spatial_entity,XR_FB_spatial_entity_storage,XR_FB_spatial_entity_query,XR_FB_spatial_entity_user,XR_FB_spatial_entity_storage_batch,XR_FB_spatial_entity_sharing,XR_META_spatial_entity_persistence,XR_META_spatial_entity_discovery,XR_META_spatial_entity_group_sharing,XR_META_spatial_entity_mesh,XR_META_spatial_entity_sharing,XR_META_boundary_visibility,XR_META_colocation_discovery,XR_METAX1_dynamic_object_tracker,XR_META_dynamic_object_tracker,XR_META_dynamic_object_keyboard,XR_META_environment_depth,XR_META_virtual_keyboard,XR_EXT_local_floor,XR_EXT_active_action_set_priority,XR_FB_haptic_amplitude_envelope,XR_FB_haptic_pcm,XR_FB_touch_controller_pro,XR_META_touch_controller_plus,XR_FB_touch_controller_proximity,XR_OCULUS_external_camera,XR_META_detached_controllers,XR_LOGITECH_mx_ink_stylus_interaction,XR_FBX1_touch_controller_extras,XR_EXT_palm_pose
[Unity.exe (44236)] 21/03 15:58:10.381 {!ERROR!} [OXR] xrCreateInstance: Extension XR_META_hand_tracking_microgestures requires extension XR_EXT_hand_interaction, which was not specified
[Unity.exe (44236)] 21/03 15:58:10.381 {INFO}    [CAPI] ovr_Shutdown_Impl called.`

Here's Unity Editor Log: 
`Filename: ./Library/PackageCache/com.meta.xr.sdk.avatars@f8c08797bc66/Scripts/OvrAvatarLog.cs Line: 211)

Refreshing native plugins compatible for Editor in 5.10 ms, found 11 plugins.
The project currently uses the compatibility mode where the Render Graph API is disabled. Support for this mode will be removed in future Unity versions. Migrate existing ScriptableRenderPasses to the new RenderGraph API. After the migration, disable the compatibility mode in Edit > Projects Settings > Graphics > Render Graph.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogWarning (object)
UnityEngine.Rendering.Universal.WarnUsingNonRenderGraph:EmitConsoleWarning () (at ./Library/PackageCache/com.unity.render-pipelines.universal@087c6d6dbb7d/Runtime/Data/UniversalRenderPipelineAsset.cs:427)
System.Reflection.RuntimeMethodInfo:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MethodBase:Invoke (object,object[])
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadMethodAttributes ()

(Filename: ./Library/PackageCache/com.unity.render-pipelines.universal@087c6d6dbb7d/Runtime/Data/UniversalRenderPipelineAsset.cs Line: 427)

[MODES] ModeService[none].Initialize
[MODES] ModeService[none].LoadModes
Mono: successfully reloaded assembly
- Finished resetting the current domain, in  1.481 seconds
Domain Reload Profiling: 2205ms
	BeginReloadAssembly (520ms)
		ExecutionOrderSort (1ms)
		DisableScriptedObjects (51ms)
		BackupInstance (0ms)
		ReleaseScriptingObjects (1ms)
		CreateAndSetChildDomain (339ms)
	RebuildCommonClasses (23ms)
	RebuildNativeTypeToScriptingClass (9ms)
	initialDomainReloadingComplete (19ms)
	LoadAllAssembliesAndSetupDomain (153ms)
		LoadAssemblies (102ms)
		RebuildTransferFunctionScriptingTraits (0ms)
		AnalyzeDomain (120ms)
			TypeCache.Refresh (5ms)
				TypeCache.ScanAssembly (0ms)
			BuildScriptInfoCaches (99ms)
			ResolveRequiredComponents (13ms)
	FinalizeReload (1481ms)
		ReleaseScriptCaches (0ms)
		RebuildScriptCaches (0ms)
		SetupLoadedEditorAssemblies (665ms)
			LogAssemblyErrors (0ms)
			InitializePlatformSupportModulesInManaged (28ms)
			SetLoadedEditorAssemblies (3ms)
			BeforeProcessingInitializeOnLoad (94ms)
			ProcessInitializeOnLoadAttributes (468ms)
			ProcessInitializeOnLoadMethodAttributes (68ms)
			AfterProcessingInitializeOnLoad (5ms)
			EditorAssembliesLoaded (0ms)
		ExecutionOrderSort2 (1ms)
		AwakeInstancesAfterBackupRestoration (379ms)
Asset Pipeline Refresh (id=044faa185988a7e46902337f2bd8635a): Total: 2.373 seconds - Initiated by StopAssetImportingV2(ForceSynchronousImport | ForceDomainReload)
	Summary:
		Imports: total=0 (actual=0, local cache=0, cache server=0)
		Asset DB Process Time: managed=0 ms, native=1585 ms
		Asset DB Callback time: managed=28 ms, native=1 ms
		Scripting: domain reloads=1, domain reload time=756 ms, compile time=1 ms, other=0 ms
		Project Asset Count: scripts=1918, non-scripts=3915
		Asset File Changes: new=0, changed=0, moved=0, deleted=0
		Scan Filter Count: 0
	InvokeCustomDependenciesCallbacks: 0.001ms
	InvokePackagesCallback: 6.381ms
	ApplyChangesToAssetFolders: 0.368ms
	Scan: 0.000ms
	OnSourceAssetsModified: 0.001ms
	CategorizeAssetsWithTransientArtifact: 0.002ms
	ProcessAssetsWithTransientArtifactChanges: 2.822ms
	CategorizeAssets: 56.307ms
	ImportOutOfDateAssets: 1496.551ms (1492.511ms without children)
		CompileScripts: 1.101ms
		CollectScriptTypesHashes: 0.524ms
		ReloadNativeAssets: 1.176ms
		UnloadImportedAssets: 0.019ms
		EnsureUptoDateAssetsAreRegisteredWithGuidPM: 0.724ms
		InitializingProgressBar: 0.000ms
		PostProcessAllAssetNotificationsAddChangedAssets: 0.000ms
		OnDemandSchedulerStart: 0.495ms
	PostProcessAllAssets: 28.794ms
	GatherAllCurrentPrimaryArtifactRevisions: 0.246ms
	UnloadStreamsBegin: 0.002ms
	PersistCurrentRevisions: 0.198ms
	UnloadStreamsEnd: 0.001ms
	GenerateScriptTypeHashes: 7.556ms
	Untracked: 781.105ms

[XR] Oculus settings : 
	Shared Depth Buffer: Yes
	Dash Support: Yes
	Requested Stereo Rendering Mode Single Pass Instanced
	Color Space: Linear
	Low Overhead Mode: No
	Optimize Buffer Discards: Yes
	Symmetric Projection: Yes
	Subsampled Layout: No
	Foveated Rendering Method: Fixed Foveated Rendering
	Late Latching: No
	Late Latching Debug: No
	Enable TrackingOrigin Stage Mode: No
	Depth Testing: No
[Subsystems] Loading plugin OculusXRPlugin for subsystem oculus display...
[OVRPlugin][INFO] OpenXR SDK version 1.1.42[OVRPlugin][INFO] Available Extensions: (80)[OVRPlugin][INFO]  Name=XR_EXT_hand_tracking SpecVersion=4[OVRPlugin][INFO]  Name=XR_HTC_hand_interaction SpecVersion=1[OVRPlugin][INFO]  Name=XR_EXT_hand_interaction SpecVersion=1[OVRPlugin][INFO]  Name=XR_EXT_eye_gaze_interaction SpecVersion=1[OVRPlugin][INFO]  Name=XR_HTC_facial_tracking SpecVersion=1[OVRPlugin][INFO]  Name=XR_HTC_eye_tracker SpecVersion=1[OVRPlugin][INFO]  Name=XR_HTC_passthrough SpecVersion=1[OVRPlugin][INFO]  Name=XR_HTC_path_enumeration SpecVersion=1[OVRPlugin][INFO]  Name=XR_HTC_vive_xr_tracker_interaction SpecVersion=1[OVRPlugin][INFO]  Name=XR_HTC_body_tracking SpecVersion=1[OVRPlugin][INFO]  Name=XR_KHR_D3D11_enable SpecVersion=9[OVRPlugin][INFO]  Name=XR_KHR_D3D12_enable SpecVersion=9[OVRPlugin][INFO]  Name=XR_KHR_opengl_enable SpecVersion=10[OVRPlugin][INFO]  Name=XR_KHR_vulkan_enable SpecVersion=8[OVRPlugin][INFO]  Name=XR_KHR_vulkan_enable2 SpecVersion=2[OVRPlugin][INFO]  Name=XR_KHR_composition_layer_depth SpecVersion=6[OVRPlugin][INFO]  Name=XR_KHR_win32_convert_performance_counter_time SpecVersion=1[OVRPlugin][INFO]  Name=XR_KHR_convert_timespec_time SpecVersion=1[OVRPlugin][INFO]  Name=XR_KHR_composition_layer_cube SpecVersion=8[OVRPlugin][INFO]  Name=XR_KHR_composition_layer_cylinder SpecVersion=4[OVRPlugin][INFO]  Name=XR_KHR_composition_layer_equirect SpecVersion=3[OVRPlugin][INFO]  Name=XR_KHR_visibility_mask SpecVersion=2[OVRPlugin][INFO]  Name=XR_KHR_composition_layer_color_scale_bias SpecVersion=5[OVRPlugin][INFO]  Name=XR_EXT_win32_appcontainer_compatible SpecVersion=1[OVRPlugin][INFO]  Name=XR_EXT_debug_utils SpecVersion=5[OVRPlugin][INFO]  Name=XR_OCULUS_recenter_event SpecVersion=1[OVRPlugin][INFO]  Name=XR_OCULUS_audio_device_guid SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_color_space SpecVersion=3[OVRPlugin][INFO]  Name=XR_FB_display_refresh_rate SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_performance_metrics SpecVersion=2[OVRPlugin][INFO]  Name=XR_META_headset_id SpecVersion=2[OVRPlugin][INFO]  Name=XR_OCULUS_ovrsession_handle SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_hand_tracking_aim SpecVersion=2[OVRPlugin][INFO]  Name=XR_FB_hand_tracking_capsules SpecVersion=3[OVRPlugin][INFO]  Name=XR_FB_hand_tracking_mesh SpecVersion=3[OVRPlugin][INFO]  Name=XR_EXT_hand_tracking_data_source SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_hand_tracking_microgestures SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_simultaneous_hands_and_controllers SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_body_tracking SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_body_tracking_full_body SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_body_tracking_fidelity SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_body_tracking_calibration SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_passthrough SpecVersion=4[OVRPlugin][INFO]  Name=XR_META_passthrough_layer_resumed_event SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_triangle_mesh SpecVersion=2[OVRPlugin][INFO]  Name=XR_META_passthrough_color_lut SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_passthrough_preferences SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_render_model SpecVersion=4[OVRPlugin][INFO]  Name=XR_FB_spatial_entity_container SpecVersion=2[OVRPlugin][INFO]  Name=XR_FB_scene SpecVersion=4[OVRPlugin][INFO]  Name=XR_FB_spatial_entity SpecVersion=3[OVRPlugin][INFO]  Name=XR_FB_spatial_entity_storage SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_spatial_entity_query SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_spatial_entity_user SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_spatial_entity_storage_batch SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_spatial_entity_sharing SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_spatial_entity_persistence SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_spatial_entity_discovery SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_spatial_entity_group_sharing SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_spatial_entity_mesh SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_spatial_entity_sharing SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_boundary_visibility SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_colocation_discovery SpecVersion=1[OVRPlugin][INFO]  Name=XR_METAX1_dynamic_object_tracker SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_dynamic_object_tracker SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_dynamic_object_keyboard SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_environment_depth SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_virtual_keyboard SpecVersion=1[OVRPlugin][INFO]  Name=XR_EXT_local_floor SpecVersion=1[OVRPlugin][INFO]  Name=XR_EXT_active_action_set_priority SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_haptic_amplitude_envelope SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_haptic_pcm SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_touch_controller_pro SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_touch_controller_plus SpecVersion=1[OVRPlugin][INFO]  Name=XR_FB_touch_controller_proximity SpecVersion=1[OVRPlugin][INFO]  Name=XR_OCULUS_external_camera SpecVersion=1[OVRPlugin][INFO]  Name=XR_META_detached_controllers SpecVersion=1[OVRPlugin][INFO]  Name=XR_LOGITECH_mx_ink_stylus_interaction SpecVersion=1[OVRPlugin][INFO]  Name=XR_FBX1_touch_controller_extras SpecVersion=1[OVRPlugin][INFO]  Name=XR_EXT_palm_pose SpecVersion=3[OVRPlugin][INFO] Unavailable OpenXR extension: XR_EXT_performance_settings[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_swapchain_update_state[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_swapchain_update_state_vulkan[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_foveation[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_foveation_configuration[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_foveation_vulkan[OVRPlugin][INFO] Unavailable OpenXR extension: XR_META_vulkan_swapchain_create_info[OVRPlugin][INFO] Unavailable OpenXR extension: XR_META_foveation_eye_tracked[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_composition_layer_image_layout[OVRPlugin][INFO] Unavailable OpenXR extension: XR_KHR_composition_layer_equirect2[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_passthrough_keyboard_hands[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_common_events[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_keyboard_tracking[OVRPlugin][INFO] Unavailable OpenXR extension: XR_EXT_hand_joints_motion_range[OVRPlugin][INFO] Unavailable OpenXR extension: XR_META_hand_tracking_wide_motion_mode[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_face_tracking[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_face_tracking2[OVRPlugin][INFO] Unavailable OpenXR extension: XR_METAX1_face_tracking_visemes[OVRPlugin][INFO] Unavailable OpenXR extension: XR_FB_eye_tracking_social[OVRPlugin][INFO] Unavailable OpenXR extension: XR_MSFT_hand_interaction[OVRPlugin][INFO] Unavailable OpenXR extension: XR_EXT_futureError [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance chained CreateInstance call failed
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed
[OVRPlugin][ERROR] [XRCMD][failure] [XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED]: xrCreateInstance(&createInfo, &instance), arvr\projects\integrations\OVRPlugin\Src\Util\CompositorOpenXR.cpp:4345 (arvr\projects\integrations\OVRPlugin\Src\Util/CompositorOpenXR.h:342)[OVRPlugin][INFO] Initialize: xrCreateInstance() failed[OVRPlugin][ERROR] Plugin failed to initialize. (arvr\projects\integrations\OVRPlugin\Src\Util\CompositorOpenXR.cpp:2693)[XR] OVRPlugin failed to initialize.
[XR] Oculus XR Plugin Failed to initialize OVR plugin.
[Subsystems] Failed to initialize subsystem oculus display [error: 1]
[Subsystems] Loading plugin OculusXRPlugin for subsystem oculus input...
[XR] XR input Oculus failed to initialize OVR plugin.
[Subsystems] Failed to initialize subsystem oculus input [error: 1]
Unable to start Oculus XR Plugin.
Possible causes include a headset not being attached, or the Oculus runtime is not installed or up to date.
If you've recently installed or updated the Oculus runtime, you may need to reboot or close Unity and the Unity Hub and try again.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogWarning (object)
Unity.XR.Oculus.OculusLoader:Initialize () (at ./Library/PackageCache/com.unity.xr.oculus@0d7d101b4114/Runtime/OculusLoader.cs:193)
UnityEngine.XR.Management.XRManagerSettings:InitializeLoaderSync () (at ./Library/PackageCache/com.unity.xr.management@3126858600e6/Runtime/XRManagerSettings.cs:190)
UnityEngine.XR.Management.XRGeneralSettings:InitXRSDK () (at ./Library/PackageCache/com.unity.xr.management@3126858600e6/Runtime/XRGeneralSettings.cs:175)
UnityEngine.XR.Management.XRGeneralSettings:AttemptInitializeXRSDKOnLoad () (at ./Library/PackageCache/com.unity.xr.management@3126858600e6/Runtime/XRGeneralSettings.cs:148)

(Filename: ./Library/PackageCache/com.unity.xr.oculus@0d7d101b4114/Runtime/OculusLoader.cs Line: 193)

Found IOVRSkeletonDataProvider reference in RightOVRHand due to unassigned field.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRSkeleton:Awake () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/Util/OVRSkeleton.cs:520)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/Util/OVRSkeleton.cs Line: 520)

Found IOVRSkeletonDataProvider reference in LeftOVRHand due to unassigned field.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRSkeleton:Awake () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/Util/OVRSkeleton.cs:520)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/Util/OVRSkeleton.cs Line: 520)

Your project uses a scriptable render pipeline. You can use Camera.stereoTargetEye only with the built-in renderer.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogWarning (object)
UnityEngine.Camera:set_stereoTargetEye (UnityEngine.StereoTargetEyeMask)
OVRCameraRig:EnsureGameObjectIntegrity () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs:609)
OVRCameraRig:Awake () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs:196)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs Line: 609)

Your project uses a scriptable render pipeline. You can use Camera.stereoTargetEye only with the built-in renderer.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogWarning (object)
UnityEngine.Camera:set_stereoTargetEye (UnityEngine.StereoTargetEyeMask)
OVRCameraRig:EnsureGameObjectIntegrity () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs:610)
OVRCameraRig:Awake () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs:196)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs Line: 610)

Your project uses a scriptable render pipeline. You can use Camera.stereoTargetEye only with the built-in renderer.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogWarning (object)
UnityEngine.Camera:set_stereoTargetEye (UnityEngine.StereoTargetEyeMask)
OVRCameraRig:EnsureGameObjectIntegrity () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs:611)
OVRCameraRig:Awake () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs:196)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRCameraRig.cs Line: 611)

[OVRManager] OnApplicationPause(false)
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRManager:OnApplicationPause (bool) (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs:3459)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs Line: 3459)

[OVRManager] OnApplicationFocus(true)
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRManager:OnApplicationFocus (bool) (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs:3467)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs Line: 3467)

Loaded scene 'Temp/__Backupscenes/0.backup'
	Deserialize:            31.732 ms
	Integration:            357.022 ms
	Integration of assets:  0.033 ms
	Thread Wait Time:       -0.029 ms
	Total Operation Time:   388.758 ms
Exception occured during OvrPlatform init - Update your app id by selecting 'Oculus Platform' -> 'Edit Settings'
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
Oculus.Platform.BuildingBlocks.EntitlementCheck:PerformUserEntitlementCheck () (at ./Library/PackageCache/com.meta.xr.sdk.platform@e0746921a1c5/Scripts/BuildingBlocks/EntitlementCheck/EntitlementCheck.cs:56)
Oculus.Platform.BuildingBlocks.EntitlementCheck:Start () (at ./Library/PackageCache/com.meta.xr.sdk.platform@e0746921a1c5/Scripts/BuildingBlocks/EntitlementCheck/EntitlementCheck.cs:42)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.platform@e0746921a1c5/Scripts/BuildingBlocks/EntitlementCheck/EntitlementCheck.cs Line: 56)

Unable to process a controller whose SampleRateHz is 0 now.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRHaptics/OVRHapticsOutput:Process () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRHaptics.cs:176)
OVRHaptics:Process () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRHaptics.cs:393)
OVRManager:LateUpdate () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs:3398)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRHaptics.cs Line: 176)

Unable to process a controller whose SampleRateHz is 0 now.
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRHaptics/OVRHapticsOutput:Process () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRHaptics.cs:176)
OVRHaptics:Process () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRHaptics.cs:393)
OVRManager:LateUpdate () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs:3398)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRHaptics.cs Line: 176)

[Licensing::Client] Successfully resolved entitlement details
[OVRManager] OnApplicationFocus(false)
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRManager:OnApplicationFocus (bool) (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs:3471)
UnityEditor.PlayModeView:SetFocus (bool)
UnityEditor.GameView:OnLostFocus ()
UnityEditor.HostView:OnLostFocus ()

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs Line: 3471)

[OVRManager] OnApplicationQuit
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRManager:OnApplicationQuit () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs:3477)

(Filename: ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs Line: 3477)

[OVRManager] OnDestroy
UnityEngine.Debug:ExtractStackTraceNoAlloc (byte*,int,string)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
OVRManager:OnDestroy () (at ./Library/PackageCache/com.meta.xr.sdk.core@ac41be98e9d0/Scripts/OVRManager.cs:3444)
`

**Comment by quangtnv** [comment]
Hi, thanks for the suggestion, I also came across that thread when looking for answers and I don't think it's the problem. I've set my Oculus as Default OpenXR runtime. Meanwhile, it also doesn't make sense that if this the case (SteamVR as OpenXR runtime), why would v72 launch and not v74?

**Comment by LMBooth** [comment]
I'm having a similar issue, so best to roll back to v72? i have for the associated meta packages but now i have 38 import errors  all relating to MetaCodeSampleAttribute and MetaCodeSample? 

![Image](https://github.com/user-attachments/assets/325d0b71-95ea-4d99-9638-6b223f556dec)

Should i be using OpenXR Hand too as i keep being prompted to instead of OVR hand? - I still have Oculus selected in the XR Plug-in management tab in project settings.

**Comment by LMBooth** [comment]
Actually, i got it working on my quest 3 after deleting and unzipping the package from scratch again, still is an issue with the depth example but for some of the pasthrough transitions seemed to work fine.

**Comment by quangtnv** [comment]
After testing on another device, (PC, Windows 11, RTX 4080), re-cloning the project on that machine and it works. So this is a machine specific issue then. It is pretty weird on my case, I'll close the issue for now and update on the fix when I found one since it looks like only my laptop experiencing this bug.

**Comment by mattephi** [comment]
I think it is an issue with v74 sdk, including 74.0.1, play mode simply does not use link and does not start on headset. This even happens when you create the project from scratch adding only camera rig from meta sdk core. However, downgrading to 72 resolves the issue and link starts working properly

My mahine is
PC, Win 11, 4070TiS

**Comment by quangtnv** [comment]
Seems like others also experience same issue too and my laptop (Windows 10, RTX 4090) is still a brick with v74: 
[Thread 1](https://communityforums.atmeta.com/t5/Get-Help/Quest-2-Link-cable-connection-isn-t-working-after-update-to-v74/td-p/1307949)
[Thread 2](https://communityforums.atmeta.com/t5/Get-Help/Quest-Link-stopped-working-suddenly/td-p/1308267)

**Comment by quangtnv** [comment]
For anyone who tumbled across this thread, I fixed it by update my NVIDIA driver to the latest, uninstalled Vive Business Streaming and SteamVR, restart the machine.
